build_number = number_of_commits

platform :android do
  lane :storybook do |options|

    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'android/',
    )

    appetize(
      path: "android/app/build/outputs/apk/release/app-release.apk",
      api_token: "tok_mlqypjmhhzwfgrcjrc2ysx536u",
      public_key: "ikryxly7ciwnmhh35ml63vg3pm",
      platform: "android",
      note: "Fluid - #{build_number}"
    )
  end
end
